services:
  artery:
    build:
      context: ${CAVISE_ROOT}
      dockerfile: ${PATH_TO_ARTERY}/Dockerfile
    image: artery:local
    container_name: artery
    command: ["sh", "-c", "sleep infinity"]
    networks:
      highly_accurate_network:
        ipv4_address: 8.8.0.12
    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=${XAUTHORITY}
    privileged: true
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
              driver: nvidia
    volumes:
      - ${CAVISE_ROOT}/simdata:/cavise/simdata
      - ${PATH_TO_ARTERY}/scenarios/:/cavise/artery/scenarios/
      - /usr/share/vulkan/icd.d:/usr/share/vulkan/icd.d
      - /tmp/.X11-unix:/tmp/.X11-unix

  carla:
    build:
      context: ${CAVISE_ROOT}
      dockerfile: ${PATH_TO_CARLA}/Dockerfile
    image: carla:local
    container_name: carla
    command: ["sh", "-c", "sleep infinity"]
    networks:
      highly_accurate_network:
        ipv4_address: 8.8.0.11
    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=${XAUTHORITY}
    privileged: true
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
              driver: nvidia
    volumes:
      - /usr/share/vulkan/icd.d:/usr/share/vulkan/icd.d
      - /tmp/.X11-unix:/tmp/.X11-unix

  opencda:
    build:
      context: ${CAVISE_ROOT}
      dockerfile: ${PATH_TO_OPENCDA}/Dockerfile
      args:
        UID: 1000  # Example: use your actual UID from `echo $UID`
    image: opencda:local
    container_name: opencda
    command: ["sh", "-c", "sleep infinity"]
    networks:
      highly_accurate_network:
        ipv4_address: 8.8.0.10
    environment:
      - DISPLAY=${DISPLAY}
    privileged: true
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
              driver: nvidia
    volumes:
      - ${CAVISE_ROOT}/cavise/messages:/home/opencda/cavise/messages
      - ${CAVISE_ROOT}/simdata:/home/opencda/cavise/simdata
      - ${PATH_TO_OPENCDA}:/home/opencda/cavise/opencda
      - ${PATH_TO_SUMO}/assets:/home/opencda/cavise/opencda/opencda/sumo-assets
      - /usr/share/vulkan/icd.d:/usr/share/vulkan/icd.d
      - /tmp/.X11-unix:/tmp/.X11-unix

  sumo:
    build:
      context: ${CAVISE_ROOT}
      dockerfile: ${PATH_TO_SUMO}/Dockerfile
    image: sumo:local
    container_name: sumo
    command: ["sh", "-c", "sleep infinity"]
    networks:
      highly_accurate_network:
        ipv4_address: 8.8.0.7
    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=${XAUTHORITY}
    privileged: true
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
              driver: nvidia
    volumes:
      - ${PATH_TO_SUMO}/assets:/home/sumo/assets
      - /tmp/.X11-unix:/tmp/.X11-unix

networks:
  highly_accurate_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 8.8.0.0/16
